build:
  version: "3.0"

spring:
  application:
    name: "cards"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

cards:
  message: "Welcome to EazyBank cards related default profile APIs - 1 "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932
