build:
  version: "2.0"

spring:
  application:
    name: "cards"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267
