build:
  version: "1.0"

spring:
  application:
    name: "cards"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

cards:
  message: "Hey, welcome to EazyBank cards related prod APIs - 4"
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@eazybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721
