build:
  version: "1.0"


spring:
  application:
    name: "loans"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

loans:
  message: "Hey, welcome to EazyBank loans related prod APIs - 4"
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956
