build:
  version: "3.0"

spring:
  application:
    name: "loans"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

loans:
  message: "Welcome to EazyBank loans related default profile APIs - 1"
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
